[package]
name = "flight-computer"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "flight-computer"
harness = false


[dependencies]
embedded-hal = "0.2.7"
log = "0.4"
esp-idf-svc = { version = "0.52.1", features = ["critical-section", "embassy-time-driver", "embassy-sync"] }
embassy-time = { version = "0.5", features = ["generic-queue-8"] }
esp-idf-hal = "0.46.2"
mpu6050 = "0.1.6"
shared-bus = "0.3.1"
bmp280-ehal = "0.0.6"
nalgebra = "0.31.4"
libm = "0.2.16"

[build-dependencies]
embuild = "0.33"

[package.metadata.esp-idf-sys]
esp_idf_config = ["CONFIG_ESP_MAIN_TASK_STACK_SIZE=65536"]
